// AUTO-GENERATED by scripts/gen-ai-changelog.mjs (prebuild). Elle duzenleme.
export const AI_CHANGELOG_GENERATED = "2026-06-20";
export interface AiChangelogEntry { hash: string; date: string; subject: string; }
export const AI_CHANGELOG: AiChangelogEntry[] = [
  {
    "hash": "6865e0be",
    "date": "2026-06-20",
    "subject": "feat(events): canlı etkinlik modu — geri sayım + Canlı Başlat/Bitir + canlı konuşmacı puanı"
  },
  {
    "hash": "8d75273a",
    "date": "2026-06-20",
    "subject": "feat(functions): etkinlik başlangıcında organizatöre \"başlatayım mı?\" bildirimi"
  },
  {
    "hash": "b337592b",
    "date": "2026-06-20",
    "subject": "feat(super-admin): taslak (ön kayıt) STK'ları onayla → Aktif + doğrulanmış"
  },
  {
    "hash": "3d331384",
    "date": "2026-06-20",
    "subject": "feat(events): super-admin tam düzenleme + organizatör logosu + geri sayım + canlı/tıklanabilir"
  },
  {
    "hash": "9ab70b83",
    "date": "2026-06-20",
    "subject": "feat(org): coral doğrulama tiki STK liste kartında da göster"
  },
  {
    "hash": "710d1fab",
    "date": "2026-06-20",
    "subject": "feat(yetkili): super-admin tam kontrol + sahip her zaman listelensin"
  },
  {
    "hash": "03d8ee32",
    "date": "2026-06-20",
    "subject": "feat(events): 'Tamamla = kapat' — tamamlanan etkinlik aktif/canlı listeden düşer"
  },
  {
    "hash": "40934b55",
    "date": "2026-06-20",
    "subject": "feat(org): coral doğrulama tiki (VerifiedBadge) — STK profilinde"
  },
  {
    "hash": "331b260e",
    "date": "2026-06-20",
    "subject": "feat: kütük no tireleri otomatik + hoş geldin puanı (hangel rozeti)"
  },
  {
    "hash": "2a8f7509",
    "date": "2026-06-20",
    "subject": "chore(audit): 'yarat-' (oluşturma fiili) → 'üret/oluştur' (Apple/dil kuralı)"
  },
  {
    "hash": "0d348c75",
    "date": "2026-06-20",
    "subject": "feat(org): çok-tipli kuruluş ön kayıt (dernek/vakıf/kulüp) + İngilizce route"
  },
  {
    "hash": "be94f1de",
    "date": "2026-06-20",
    "subject": "fix(ngo-admin): aktif kuruluşu URL'de kanonikleştir (giriş karmaşasını bitir)"
  },
  {
    "hash": "485574f9",
    "date": "2026-06-20",
    "subject": "feat(stk): hızlı STK ön kayıt — kütükten sahiplen (taslak) + ikaz banner"
  },
  {
    "hash": "e0c9b5e1",
    "date": "2026-06-20",
    "subject": "feat(events): katılım puanı kayıttan TAMAMLAMAYA taşındı + kurumsal teşekkür metni"
  },
  {
    "hash": "df2de356",
    "date": "2026-06-20",
    "subject": "feat(events): 'Etkinliği Tamamla' butonu + completion akışı"
  },
  {
    "hash": "43f8248b",
    "date": "2026-06-20",
    "subject": "feat(events): RSVP'de etkinlik katılım puanı (+20 impact) — ilk 'going'de"
  },
  {
    "hash": "fe67f69f",
    "date": "2026-06-20",
    "subject": "fix(ngo-admin): aktif kuruluş değiştirme + founder yetkisi"
  },
  {
    "hash": "7936092e",
    "date": "2026-06-20",
    "subject": "fix(app): native uygulamada çerez popup'ı gösterme (zaten app'teyiz)"
  },
  {
    "hash": "48b94b68",
    "date": "2026-06-20",
    "subject": "fix(ngo-admin/users): yetkili listesi AKTİF kuruluşa göre gelsin (çoklu kurum)"
  },
  {
    "hash": "64a9c037",
    "date": "2026-06-20",
    "subject": "feat(kurumsal): yetkili kişi telefonuyla otomatik yetkilendirme (onay + kayıt)"
  },
  {
    "hash": "915f7445",
    "date": "2026-06-20",
    "subject": "fix(super-admin/ngos): Yetkili diyaloğu STK'nın TÜM yetkililerini rolleriyle listelesin"
  },
  {
    "hash": "30673cc1",
    "date": "2026-06-20",
    "subject": "fix(ngo-admin/users): yetkili listeleme + rol değiştir/çıkar Admin SDK ile çalışsın"
  },
  {
    "hash": "fff30ea7",
    "date": "2026-06-20",
    "subject": "feat(appclip): /clip landing sayfası (App Clip Default Experience URL + tarayıcı fallback)"
  },
  {
    "hash": "66877b5e",
    "date": "2026-06-20",
    "subject": "fix(appclip): canlı AASA'ya appclips + webcredentials eklendi (App Clip engeli)"
  },
  {
    "hash": "0700746d",
    "date": "2026-06-19",
    "subject": "fix(certificate): Apple kimliğinde yeniden tasarım — Türkçe font sorunu çözüldü"
  }
];
