/**
 * hangel AI Bağlam Paketi — Claude/ChatGPT'ye verilecek kalıcı bağlam metni.
 *
 * Tek kaynak: bu sabit. Süper Admin → Ayarlar → "Yapay Zekalar ile Entegrasyon"
 * bölümünde gösterilir + kopyalanır. hangel'de büyük bir değişiklik olduğunda
 * BU SABİT güncellenir → panel otomatik güncel kalır. (Repo kopyası:
 * docs/hangel-context-pack.md — ikisi senkron tutulur.)
 *
 * SIR YOK: API anahtarı / şifre / token buraya ASLA yazılmaz (dış servise gider).
 */
export const HANGEL_AI_CONTEXT_UPDATED = '2026-06-11';

export const HANGEL_AI_CONTEXT = [
  'hangel — AI Bağlam Paketi (güncel: 2026-06-11)',
  'Marka adı her zaman küçük harf: "hangel". Yanıtlar Türkçe. 🙏 emoji kullanma (yerine 🧡).',
  'Bu metinde SIR yoktur (API anahtarı/şifre/token yok).',
  '',
  '1) TEK CÜMLE',
  'hangel; STK\'lar, markalar, öğrenci kulüpleri ve kullanıcıları tek çatıda buluşturan, bağış-destekli sosyal ticaret + gönüllülük + sosyal etki platformudur.',
  '',
  '2) VİZYON & İŞ MODELİ',
  '- Kullanıcı markadan alışveriş yapar → hangel affiliate komisyonu kazanır → bir kısmı STK\'lara bağış olur ("bağış-destekli Cimri" + sosyal etki).',
  '- STK: bağış toplar, gönüllü yönetir, şeffaflık/etki raporlar, kendi web sitesini alır.',
  '- Marka: hem marka hem ürün bazlı listelenir (ürün feed kütüphanesi; listingMode = brand|product|both).',
  '- Öğrenci kulübü: etkinlik/üyelik/içerik. Acil durum: kan bağışı + afet çağrıları (eşleştirme + bildirim + iOS Live Activity).',
  '- Gönüllülük: ilan → başvuru → onay → tamamlama → sertifika + etki puanı.',
  '',
  '3) ÇEKİRDEK VARLIKLAR & ROLLER',
  '- User: profil, impactScore, rozet, sertifika, bağış/gönüllülük geçmişi.',
  '- NGO/STK (ngos koleksiyonu, yönetici ngo-admin), Brand/Marka (brands, brand-admin), Club (clubs, club-admin).',
  '- Roller: super-admin, ngo-admin, brand-admin, club-admin, user. Süper-admin yetkileri superAdminPermissions ile granular.',
  '',
  '4) KULLANICI MODÜLLERİ (rotalar)',
  'Market (affiliate alışveriş) + /market/products (ürün listeleme) + /products/[id]; bağış (/my-donations); gönüllülük (/volunteering, /my-applications); acil/kan (/emergency, /blood); mesajlar (/messages); bildirimler (/notifications); profil (/profile, /u/[id]); rozetler (/my-badges); liderlik; etkinlikler; içerik (/library, /posts, /stories, /press); davet (/invite); arama; STK/marka/kulüp vitrinleri; QR ödeme; onboarding akışları.',
  '',
  '5) STK YÖNETİM PANELİ (/ngo-admin/*)',
  'dashboard, donations, volunteer/volunteering/volunteer-completions/volunteer-portal, opportunities, events, posts, messaging/sms/mail/dm/inbox, crm, demographics, analytics-tools, reports, transparency, sustainability, impact-story, funds, accounting, payment-systems, brand-earnings, ecommerce, ads, community-invite, university-volunteering, field-team, hr-integration, online-meeting, virtual-office/virtual-pbx, website (STK kendi sitesi), manage-profile, users, settings, qr.',
  '',
  '6) SÜPER ADMIN PANELİ (/super-admin/*)',
  'users, ngos, brands, clubs, applications, feed (Ürün Feed & Listeleme), donations, volunteer, events, posts, emergency, hospitals, messaging/messaging-quota, communications, inbox, support, feedback, surveys, ads/ngo-ads, analytics, ai-management, data-enrichment, outreach, public-relations, contracts, pages, web-content, association-content, library, transparency, funds, demographics, activity (giriş/çıkış), set-superadmin, maintenance, setup, settings.',
  '',
  '7) BACKEND İŞLERİ (Cloud Functions)',
  'blood-match (kan eşleştirme), disaster-geofence, email-digest, sms-reminder, twilio, live-activity (iOS APNs), volunteer-cron, onNotificationCreated (push).',
  '',
  '8) TEKNOLOJİ YIĞINI & MİMARİ',
  '- Web: Next.js 15 (App Router, SSR) + React + TypeScript + Tailwind + shadcn/ui. API route hata formatı: { errorCode, message }.',
  '- Backend: Firebase — Auth, Firestore, App Hosting (web prod), Cloud Functions, FCM (push), Crashlytics. Sunucu tarafı Admin SDK (rules bypass).',
  '- Mobil: Capacitor (iOS + Android). App UZAKTAN https://hangel.org yükleyen bir WebView wrapper (server.url). ÖNEMLİ: web deploy = mobil app\'e ANINDA yansır (JS/route değişiklikleri rebuild gerektirmez; sadece native config/plugin rebuild ister).',
  '- iOS ekstra: Apple Watch, App Clip, Live Activity (Dynamic Island), Universal Links, SIWA.',
  '- Ödeme: N-Kolay (POS). E-posta: Resend. AI: Genkit.',
  '- CI/CD: GitHub (hangelapp/new-app) → main push → App Hosting otomatik build (web). Mobil: Codemagic (manuel) → TestFlight / Play (AAB).',
  '',
  '9) PLATFORMLAR',
  '- Web: https://hangel.org (App Hosting); STK\'lara *.hangel.org alt alan (Cloudflare for SaaS).',
  '- iOS: App Store (Team NKZNY8NU8S), bundle com.hangel.ios.app.',
  '- Android: Google Play, paket com.hangel.app (üretimde).',
  '- Chrome Extension: planlı.',
  '',
  '10) ENTEGRASYONLAR',
  '- Affiliate ağları: GelirOrtakları (ürün feed API\'si VAR: feed.gelirortaklari.com), Affocean, ReklamAction (HasOffers — sadece offer/marka, ürün feed yok).',
  '- Ürün feed platformu (kendi PIM kütüphanemiz, src/lib/feed): kanonik ürün şeması + giriş adaptörleri (gelirortaklari, generic Google Merchant XML → ikas/ideasoft/tsoft) + export (Google Merchant/Cimri/Akakçe). Ingest: /api/feed/ingest. Koleksiyon: products.',
  '- Reklam: Google/Meta/TikTok Ads (kod hazır, credential/onay bekliyor). SMS/Mail kota sistemi (havuz + N-Kolay POS).',
  '',
  '11) ALTYAPI (sır yok, sadece referans)',
  '- Firebase projesi: hangel-new-v18-87297865-9bcc3. GitHub: hangelapp/new-app (main). Domain: hangel.org.',
  '- Bazı hesaplar farklı maillerde (ör. Play şu an ihadiguzel@gmail.com); hepsini ismailhilmi@hangel.org altında toplama hedefi var.',
  '',
  '12) KOD & ÇALIŞMA STANDARTLARI',
  '- Cerrahi edit; gereksiz refactor/abstraction yok. Yeni "as any" / "@ts-ignore" / üretimde console.log yok.',
  '- Türkçe metin; kullanıcıya görünen her yerde "hangel" küçük harf. 🙏 asla (yerine 🧡).',
  '- Gate: npm run typecheck (hızlı), npm run build (prod — dynamic route/tip değişiminde zorunlu), firestore.rules değişiminde dikkat.',
  '- Deploy: web otomatik (main push), mobil Codemagic. Repo\'da Claude Code için CLAUDE.md (ajan orkestrasyon) var.',
  '',
  'GÜVENLİK: API anahtarı / panel şifresi / token AI sohbetine veya knowledge\'ına ASLA konmaz; gerekiyorsa tarif et, değerini paylaşma.',
].join('\n');

/**
 * Kısa yönerge — AI araçlarının "Custom Instructions / System prompt / GPT
 * Instructions" alanına yapıştırmak için (knowledge değil, talimat). Tek paragraf.
 */
export const HANGEL_AI_SHORT = [
  'hangel: STK, marka, öğrenci kulübü ve kullanıcıları buluşturan bağış-destekli',
  'sosyal ticaret + gönüllülük + sosyal etki platformu. Marka adı her zaman küçük "hangel".',
  'Stack: Next.js 15 (App Hosting / hangel.org) + Firebase + Capacitor (iOS/Android,',
  'uzaktan hangel.org yükler → web deploy mobile anında yansır). Markalar hem marka',
  'hem ürün bazlı listelenir (affiliate komisyonu → bağış). Türkçe yanıt ver,',
  'cerrahi ve üretim-kalitesinde kod yaz, 🙏 emoji kullanma (yerine 🧡). API anahtarı/şifre',
  'isteme/paylaşma. Detaylı bağlam için "hangel bağlam paketi"ni kullan.',
].join(' ');

export const HANGEL_AI_SHORT_EN = [
  'hangel: a donation-powered social-commerce + volunteering + social-impact platform',
  'connecting NGOs, brands, student clubs and users. Brand name is always lowercase "hangel".',
  'Stack: Next.js 15 (App Hosting / hangel.org) + Firebase + Capacitor (iOS/Android,',
  'remotely loads hangel.org → a web deploy reflects in the mobile app instantly).',
  'Brands are listed both as brands and at product level (affiliate commission → donation).',
  'Reply in Turkish, write surgical production-quality code, never use the 🙏 emoji (use 🧡),',
  'never request/share API keys or passwords. Use the "hangel context pack" for full detail.',
].join(' ');

/** English version of the context pack (for English-speaking AI sessions). */
export const HANGEL_AI_CONTEXT_EN = [
  'hangel — AI Context Pack (updated: 2026-06-11)',
  'Brand name is always lowercase: "hangel". This text contains NO secrets (no API keys/passwords/tokens).',
  '',
  '1) ONE-LINER',
  'hangel is a donation-powered social-commerce + volunteering + social-impact platform that connects NGOs, brands, student clubs and users in one place.',
  '',
  '2) VISION & BUSINESS MODEL',
  '- Users shop from brands → hangel earns affiliate commission → a share becomes a donation to NGOs ("donation-powered Cimri" + social impact).',
  '- NGOs: collect donations, manage volunteers, report transparency/impact, get their own website.',
  '- Brands: listed both as a brand and at product level (product feed library; listingMode = brand|product|both).',
  '- Student clubs: events/membership/content. Emergency: blood donation + disaster calls (matching + push + iOS Live Activity).',
  '- Volunteering: posting → application → approval → completion → certificate + impact score.',
  '',
  '3) CORE ENTITIES & ROLES',
  '- User: profile, impactScore, badges, certificates, donation/volunteering history.',
  '- NGO (ngos collection, managed by ngo-admin), Brand (brands, brand-admin), Club (clubs, club-admin).',
  '- Roles: super-admin, ngo-admin, brand-admin, club-admin, user. Super-admin scope is granular via superAdminPermissions.',
  '',
  '4) USER MODULES (routes)',
  'Market (affiliate shopping) + /market/products + /products/[id]; donations (/my-donations); volunteering (/volunteering, /my-applications); emergency/blood (/emergency, /blood); messages; notifications; profile (/profile, /u/[id]); badges; leaderboard; events; content (/library, /posts, /stories, /press); invite; search; NGO/brand/club showcases; QR payment; onboarding flows.',
  '',
  '5) NGO ADMIN PANEL (/ngo-admin/*)',
  'dashboard, donations, volunteer/volunteering/volunteer-completions/volunteer-portal, opportunities, events, posts, messaging/sms/mail/dm/inbox, crm, demographics, analytics-tools, reports, transparency, sustainability, impact-story, funds, accounting, payment-systems, brand-earnings, ecommerce, ads, community-invite, university-volunteering, field-team, hr-integration, online-meeting, virtual-office/virtual-pbx, website, manage-profile, users, settings, qr.',
  '',
  '6) SUPER ADMIN PANEL (/super-admin/*)',
  'users, ngos, brands, clubs, applications, feed (Product Feed & Listing), donations, volunteer, events, posts, emergency, hospitals, messaging/messaging-quota, communications, inbox, support, feedback, surveys, ads/ngo-ads, analytics, ai-management, data-enrichment, outreach, public-relations, contracts, pages, web-content, association-content, library, transparency, funds, demographics, activity, set-superadmin, maintenance, setup, settings.',
  '',
  '7) BACKEND JOBS (Cloud Functions)',
  'blood-match, disaster-geofence, email-digest, sms-reminder, twilio, live-activity (iOS APNs), volunteer-cron, onNotificationCreated (push).',
  '',
  '8) TECH STACK & ARCHITECTURE',
  '- Web: Next.js 15 (App Router, SSR) + React + TypeScript + Tailwind + shadcn/ui. API routes return { errorCode, message }.',
  '- Backend: Firebase — Auth, Firestore, App Hosting (web prod), Cloud Functions, FCM (push), Crashlytics. Server-side uses Admin SDK (bypasses rules).',
  '- Mobile: Capacitor (iOS + Android). The app is a WebView wrapper that REMOTELY loads https://hangel.org (server.url). IMPORTANT: a web deploy reflects in the mobile app INSTANTLY (JS/route changes need no rebuild; only native config/plugin changes require a rebuild).',
  '- iOS extras: Apple Watch, App Clip, Live Activity (Dynamic Island), Universal Links, SIWA.',
  '- Payments: N-Kolay (POS). Email: Resend. AI: Genkit.',
  '- CI/CD: GitHub (hangelapp/new-app) → push to main → App Hosting auto build (web). Mobile: Codemagic (manual) → TestFlight / Play (AAB).',
  '',
  '9) PLATFORMS',
  '- Web: https://hangel.org (App Hosting); NGOs get *.hangel.org subdomains (Cloudflare for SaaS).',
  '- iOS: App Store (Team NKZNY8NU8S), bundle com.hangel.ios.app. Android: Google Play, package com.hangel.app (in production). Chrome Extension: planned.',
  '',
  '10) INTEGRATIONS',
  '- Affiliate networks: GelirOrtaklari (HAS a product feed API: feed.gelirortaklari.com), Affocean, ReklamAction (HasOffers — offers/brands only, no product feed).',
  '- Product feed platform (our own PIM, src/lib/feed): canonical product schema + input adapters (gelirortaklari, generic Google Merchant XML → ikas/ideasoft/tsoft) + export (Google Merchant/Cimri/Akakce). Ingest: /api/feed/ingest. Collection: products.',
  '- Ads: Google/Meta/TikTok (code ready, awaiting credentials/approval). SMS/Mail quota system (pool + N-Kolay POS).',
  '',
  '11) INFRASTRUCTURE (no secrets, reference only)',
  '- Firebase project: hangel-new-v18-87297865-9bcc3. GitHub: hangelapp/new-app (main). Domain: hangel.org.',
  '- Some accounts live under different emails (e.g. Play under ihadiguzel@gmail.com); goal is to consolidate everything under ismailhilmi@hangel.org.',
  '',
  '12) CODE & WORKING STANDARDS',
  '- Surgical edits; no needless refactors/abstractions. No new "as any" / "@ts-ignore" / console.log in production.',
  '- Turkish UI text; "hangel" always lowercase in user-facing copy. Never use the 🙏 emoji (use 🧡).',
  '- Gates: npm run typecheck (fast), npm run build (prod — mandatory for dynamic route/type changes), care with firestore.rules.',
  '- Deploy: web auto (push to main), mobile via Codemagic. Repo also has CLAUDE.md (agent orchestration) for Claude Code.',
  '',
  'SECURITY: Never put API keys / panel passwords / tokens into AI chats or knowledge; describe them instead of sharing values.',
].join('\n');
