// AUTO-GENERATED by scripts/gen-ai-changelog.mjs (prebuild). Elle duzenleme.
export const AI_CHANGELOG_GENERATED = "2026-07-02";
export interface AiChangelogEntry { hash: string; date: string; subject: string; }
export const AI_CHANGELOG: AiChangelogEntry[] = [
  {
    "hash": "80464ac0",
    "date": "2026-07-02",
    "subject": "fix(events): lucide importunda duplicate 'Calendar' kaldır (webpack build kırılması)"
  },
  {
    "hash": "41999750",
    "date": "2026-07-02",
    "subject": "feat(events): kart layout FIX + mobil butonlar + Yaka Kartları/Sertifikalar + Sosyal Medya fallback"
  },
  {
    "hash": "c0a2d7e3",
    "date": "2026-07-02",
    "subject": "fix(transparency): firebase-admin type importunu kaldır (Next build '/' prerender kırılması)"
  },
  {
    "hash": "28d17894",
    "date": "2026-07-02",
    "subject": "Merge remote-tracking branch 'origin/main' into feature/all-brands-list"
  },
  {
    "hash": "b18349bc",
    "date": "2026-07-02",
    "subject": "feat(super-admin/activity): tab kategorizasyonu aktörün gerçek rolüne göre (users/{uid}.role) — invitation/notification sabit 'super-admin' yerine gerçek role"
  },
  {
    "hash": "8ecaeb84",
    "date": "2026-07-02",
    "subject": "feat(market): brands/all — ünlü markalar üstte, az bilinenler altta, grup içi rastgele"
  },
  {
    "hash": "e37b589c",
    "date": "2026-07-02",
    "subject": "fix(stk): onaylanan STK'lar ana /ngos dizininde görünsün"
  },
  {
    "hash": "2eeb4a46",
    "date": "2026-07-02",
    "subject": "feat(transparency): profil bilgileri şeffaflık endeksine + panele yansısın"
  },
  {
    "hash": "e46a4c51",
    "date": "2026-07-02",
    "subject": "Merge remote-tracking branch 'origin/main' into feature/all-brands-list"
  },
  {
    "hash": "cf337316",
    "date": "2026-07-02",
    "subject": "fix: ngo-admin doğru kurum yönlendirme + dropdown/global taşma + Etkinlik Yönetimi (dernek/vakıf/kulüp) + QR kurum logosu + belge İncele/İndir/Sil + transparency delete"
  },
  {
    "hash": "ccf1bc15",
    "date": "2026-07-02",
    "subject": "chore(market): brands-all cache v4 (195 gerçek marka logosu sitelerden)"
  },
  {
    "hash": "cd8c8e85",
    "date": "2026-07-02",
    "subject": "chore(market): brands-all cache v3 (Asus/Capcom/Anker/A4Tech logo düzeltmesi)"
  },
  {
    "hash": "83caf537",
    "date": "2026-07-02",
    "subject": "feat(market): Marka (ürün markası) ile Mağaza (satıcı) ayrımı"
  },
  {
    "hash": "977a60c5",
    "date": "2026-07-02",
    "subject": "Merge: brands-all cache v2 + 121 gerçek logo"
  },
  {
    "hash": "a71ce1ff",
    "date": "2026-07-02",
    "subject": "chore(market): brands-all cache v2 (121 gerçek logo brandDirectory'de)"
  },
  {
    "hash": "a223aa37",
    "date": "2026-07-02",
    "subject": "Merge: brands-all brandDirectory (370 markaya domain/logo)"
  },
  {
    "hash": "8c84c7cc",
    "date": "2026-07-02",
    "subject": "feat(market): brands-all brandDirectory kaynağını okur"
  },
  {
    "hash": "e8d1152d",
    "date": "2026-07-02",
    "subject": "Merge: /market/brands/all marka logoları (gerçek logo + favicon)"
  },
  {
    "hash": "291533f2",
    "date": "2026-07-02",
    "subject": "feat(market): /market/brands/all markalarına gerçek logo + favicon"
  },
  {
    "hash": "b497ccfe",
    "date": "2026-07-02",
    "subject": "Merge feature/all-brands-list: 'Tüm Markalar' tüm ürün markalarını listeler"
  },
  {
    "hash": "19fc11df",
    "date": "2026-07-02",
    "subject": "feat(market): 'Tüm Markalar' butonu tüm ürün markalarını listeler"
  },
  {
    "hash": "7a5d2106",
    "date": "2026-07-01",
    "subject": "feat(qr-login): kısa KOD + kamerasız kod-girişi + QR altında kod + Apple polish"
  },
  {
    "hash": "d454336e",
    "date": "2026-07-01",
    "subject": "feat(activity): işlem zamanına saniye + giriş/çıkış netleştir + online süre saniyeli"
  },
  {
    "hash": "9f26d901",
    "date": "2026-07-01",
    "subject": "feat(header): QR butonu cihazlar arası 'diğer cihazda aç' (adaptif)"
  },
  {
    "hash": "2e09df47",
    "date": "2026-07-01",
    "subject": "android: versionCode 32→33, versionName 2.0.9 (Play publish — 32 canlıyla çakışıyordu)"
  }
];
