// AUTO-GENERATED by scripts/gen-ai-changelog.mjs (prebuild). Elle duzenleme.
export const AI_CHANGELOG_GENERATED = "2026-07-02";
export interface AiChangelogEntry { hash: string; date: string; subject: string; }
export const AI_CHANGELOG: AiChangelogEntry[] = [
  {
    "hash": "83caf537",
    "date": "2026-07-02",
    "subject": "feat(market): Marka (ürün markası) ile Mağaza (satıcı) ayrımı"
  },
  {
    "hash": "a71ce1ff",
    "date": "2026-07-02",
    "subject": "chore(market): brands-all cache v2 (121 gerçek logo brandDirectory'de)"
  },
  {
    "hash": "8c84c7cc",
    "date": "2026-07-02",
    "subject": "feat(market): brands-all brandDirectory kaynağını okur"
  },
  {
    "hash": "291533f2",
    "date": "2026-07-02",
    "subject": "feat(market): /market/brands/all markalarına gerçek logo + favicon"
  },
  {
    "hash": "19fc11df",
    "date": "2026-07-02",
    "subject": "feat(market): 'Tüm Markalar' butonu tüm ürün markalarını listeler"
  },
  {
    "hash": "7a5d2106",
    "date": "2026-07-01",
    "subject": "feat(qr-login): kısa KOD + kamerasız kod-girişi + QR altında kod + Apple polish"
  },
  {
    "hash": "d454336e",
    "date": "2026-07-01",
    "subject": "feat(activity): işlem zamanına saniye + giriş/çıkış netleştir + online süre saniyeli"
  },
  {
    "hash": "9f26d901",
    "date": "2026-07-01",
    "subject": "feat(header): QR butonu cihazlar arası 'diğer cihazda aç' (adaptif)"
  },
  {
    "hash": "2e09df47",
    "date": "2026-07-01",
    "subject": "android: versionCode 32→33, versionName 2.0.9 (Play publish — 32 canlıyla çakışıyordu)"
  },
  {
    "hash": "6580ae15",
    "date": "2026-07-01",
    "subject": "auth: girişte Firestore role -> JWT custom claim senkronu (göç fix)"
  },
  {
    "hash": "4d7bad4c",
    "date": "2026-07-01",
    "subject": "iOS/Android: Capacitor url hangel.org.tr → hangel.org (hangelorg göçü)"
  },
  {
    "hash": "713cc420",
    "date": "2026-07-01",
    "subject": "WhatsApp OTP: bind ACCESS_TOKEN + APP_SECRET to Secret Manager"
  },
  {
    "hash": "67b230fd",
    "date": "2026-07-01",
    "subject": "migration: 8 secret -> placeholder (ilk deploy icin; gercek degerler Secret Manager'a sonra)"
  },
  {
    "hash": "615bb6b0",
    "date": "2026-07-01",
    "subject": "migration: apphosting.yaml VAPID → hangelorg web push key"
  },
  {
    "hash": "00346c42",
    "date": "2026-06-30",
    "subject": "migration: iOS/Android Firebase config → hangelorg"
  },
  {
    "hash": "4129ae33",
    "date": "2026-06-30",
    "subject": "migration: yeni projeye (hangelorg) bağla — config + SA + import/export script + runbook"
  },
  {
    "hash": "960dd54f",
    "date": "2026-06-26",
    "subject": "feat(market): sıralama çiplerini paylaşılan component yap + /market/apple'a ekle"
  },
  {
    "hash": "e2899f79",
    "date": "2026-06-26",
    "subject": "outreach arama: içerikten (kelime-öneki) arama — searchPrefixes"
  },
  {
    "hash": "dd0bd068",
    "date": "2026-06-26",
    "subject": "feat(market): arama sıralama çipleri çalışır + pazaryeri tasarımı (ikon)"
  },
  {
    "hash": "7e7933bd",
    "date": "2026-06-26",
    "subject": "outreach stats: platform/federasyon kırılımı + Apple-estetiği redesign"
  },
  {
    "hash": "45bd6994",
    "date": "2026-06-26",
    "subject": "outreach: federasyon/platform + faaliyet + kuruluş yılı süzgeçleri (tüm tablar)"
  },
  {
    "hash": "ca77c4ce",
    "date": "2026-06-26",
    "subject": "outreach: detaylı istatistik sayfası + header butonu"
  },
  {
    "hash": "6f06a186",
    "date": "2026-06-26",
    "subject": "outreach: il/ilçe/mahalle server-side süzme + adresten türetme"
  },
  {
    "hash": "4e5ff7cf",
    "date": "2026-06-25",
    "subject": "fix(ios-scroll): overscroll-behavior-y none→contain — iOS'ta sayfa kaydırma donmasın"
  },
  {
    "hash": "84944ef2",
    "date": "2026-06-25",
    "subject": "feat(legal): /google-entegrasyonu — OAuth doğrulama için uygulama amacı sayfası"
  }
];
