export interface CountryPhoneCode {
  country: string;
  code: string; // e.g. "+90"
  iso: string; // ISO 3166-1 alpha-2, e.g. "TR"
  flag: string; // emoji "🇹🇷"
}

export const COUNTRY_PHONE_CODES: CountryPhoneCode[] = [
  { country: "Türkiye", code: "+90", iso: "TR", flag: "🇹🇷" },
  { country: "KKTC", code: "+90", iso: "CY", flag: "🇨🇾" },
  { country: "Amerika Birleşik Devletleri", code: "+1", iso: "US", flag: "🇺🇸" },
  { country: "Kanada", code: "+1", iso: "CA", flag: "🇨🇦" },
  { country: "Meksika", code: "+52", iso: "MX", flag: "🇲🇽" },
  { country: "Birleşik Krallık", code: "+44", iso: "GB", flag: "🇬🇧" },
  { country: "İrlanda", code: "+353", iso: "IE", flag: "🇮🇪" },
  { country: "Almanya", code: "+49", iso: "DE", flag: "🇩🇪" },
  { country: "Fransa", code: "+33", iso: "FR", flag: "🇫🇷" },
  { country: "İtalya", code: "+39", iso: "IT", flag: "🇮🇹" },
  { country: "İspanya", code: "+34", iso: "ES", flag: "🇪🇸" },
  { country: "Portekiz", code: "+351", iso: "PT", flag: "🇵🇹" },
  { country: "Hollanda", code: "+31", iso: "NL", flag: "🇳🇱" },
  { country: "Belçika", code: "+32", iso: "BE", flag: "🇧🇪" },
  { country: "Lüksemburg", code: "+352", iso: "LU", flag: "🇱🇺" },
  { country: "İsviçre", code: "+41", iso: "CH", flag: "🇨🇭" },
  { country: "Avusturya", code: "+43", iso: "AT", flag: "🇦🇹" },
  { country: "Yunanistan", code: "+30", iso: "GR", flag: "🇬🇷" },
  { country: "Bulgaristan", code: "+359", iso: "BG", flag: "🇧🇬" },
  { country: "Romanya", code: "+40", iso: "RO", flag: "🇷🇴" },
  { country: "Macaristan", code: "+36", iso: "HU", flag: "🇭🇺" },
  { country: "Polonya", code: "+48", iso: "PL", flag: "🇵🇱" },
  { country: "Çekya", code: "+420", iso: "CZ", flag: "🇨🇿" },
  { country: "Slovakya", code: "+421", iso: "SK", flag: "🇸🇰" },
  { country: "Slovenya", code: "+386", iso: "SI", flag: "🇸🇮" },
  { country: "Hırvatistan", code: "+385", iso: "HR", flag: "🇭🇷" },
  { country: "Bosna Hersek", code: "+387", iso: "BA", flag: "🇧🇦" },
  { country: "Sırbistan", code: "+381", iso: "RS", flag: "🇷🇸" },
  { country: "Karadağ", code: "+382", iso: "ME", flag: "🇲🇪" },
  { country: "Kuzey Makedonya", code: "+389", iso: "MK", flag: "🇲🇰" },
  { country: "Arnavutluk", code: "+355", iso: "AL", flag: "🇦🇱" },
  { country: "Kosova", code: "+383", iso: "XK", flag: "🇽🇰" },
  { country: "Norveç", code: "+47", iso: "NO", flag: "🇳🇴" },
  { country: "İsveç", code: "+46", iso: "SE", flag: "🇸🇪" },
  { country: "Danimarka", code: "+45", iso: "DK", flag: "🇩🇰" },
  { country: "Finlandiya", code: "+358", iso: "FI", flag: "🇫🇮" },
  { country: "İzlanda", code: "+354", iso: "IS", flag: "🇮🇸" },
  { country: "Estonya", code: "+372", iso: "EE", flag: "🇪🇪" },
  { country: "Letonya", code: "+371", iso: "LV", flag: "🇱🇻" },
  { country: "Litvanya", code: "+370", iso: "LT", flag: "🇱🇹" },
  { country: "Rusya", code: "+7", iso: "RU", flag: "🇷🇺" },
  { country: "Ukrayna", code: "+380", iso: "UA", flag: "🇺🇦" },
  { country: "Beyaz Rusya", code: "+375", iso: "BY", flag: "🇧🇾" },
  { country: "Moldova", code: "+373", iso: "MD", flag: "🇲🇩" },
  { country: "Azerbaycan", code: "+994", iso: "AZ", flag: "🇦🇿" },
  { country: "Gürcistan", code: "+995", iso: "GE", flag: "🇬🇪" },
  { country: "Ermenistan", code: "+374", iso: "AM", flag: "🇦🇲" },
  { country: "Kazakistan", code: "+7", iso: "KZ", flag: "🇰🇿" },
  { country: "Özbekistan", code: "+998", iso: "UZ", flag: "🇺🇿" },
  { country: "Türkmenistan", code: "+993", iso: "TM", flag: "🇹🇲" },
  { country: "Kırgızistan", code: "+996", iso: "KG", flag: "🇰🇬" },
  { country: "Tacikistan", code: "+992", iso: "TJ", flag: "🇹🇯" },
  { country: "Çin", code: "+86", iso: "CN", flag: "🇨🇳" },
  { country: "Japonya", code: "+81", iso: "JP", flag: "🇯🇵" },
  { country: "Güney Kore", code: "+82", iso: "KR", flag: "🇰🇷" },
  { country: "Kuzey Kore", code: "+850", iso: "KP", flag: "🇰🇵" },
  { country: "Hindistan", code: "+91", iso: "IN", flag: "🇮🇳" },
  { country: "Pakistan", code: "+92", iso: "PK", flag: "🇵🇰" },
  { country: "Bangladeş", code: "+880", iso: "BD", flag: "🇧🇩" },
  { country: "Sri Lanka", code: "+94", iso: "LK", flag: "🇱🇰" },
  { country: "Nepal", code: "+977", iso: "NP", flag: "🇳🇵" },
  { country: "Afganistan", code: "+93", iso: "AF", flag: "🇦🇫" },
  { country: "İran", code: "+98", iso: "IR", flag: "🇮🇷" },
  { country: "Irak", code: "+964", iso: "IQ", flag: "🇮🇶" },
  { country: "Suriye", code: "+963", iso: "SY", flag: "🇸🇾" },
  { country: "Lübnan", code: "+961", iso: "LB", flag: "🇱🇧" },
  { country: "Ürdün", code: "+962", iso: "JO", flag: "🇯🇴" },
  { country: "İsrail", code: "+972", iso: "IL", flag: "🇮🇱" },
  { country: "Filistin", code: "+970", iso: "PS", flag: "🇵🇸" },
  { country: "Suudi Arabistan", code: "+966", iso: "SA", flag: "🇸🇦" },
  { country: "Birleşik Arap Emirlikleri", code: "+971", iso: "AE", flag: "🇦🇪" },
  { country: "Katar", code: "+974", iso: "QA", flag: "🇶🇦" },
  { country: "Kuveyt", code: "+965", iso: "KW", flag: "🇰🇼" },
  { country: "Bahreyn", code: "+973", iso: "BH", flag: "🇧🇭" },
  { country: "Umman", code: "+968", iso: "OM", flag: "🇴🇲" },
  { country: "Yemen", code: "+967", iso: "YE", flag: "🇾🇪" },
  { country: "Mısır", code: "+20", iso: "EG", flag: "🇪🇬" },
  { country: "Fas", code: "+212", iso: "MA", flag: "🇲🇦" },
  { country: "Cezayir", code: "+213", iso: "DZ", flag: "🇩🇿" },
  { country: "Tunus", code: "+216", iso: "TN", flag: "🇹🇳" },
  { country: "Libya", code: "+218", iso: "LY", flag: "🇱🇾" },
  { country: "Sudan", code: "+249", iso: "SD", flag: "🇸🇩" },
  { country: "Etiyopya", code: "+251", iso: "ET", flag: "🇪🇹" },
  { country: "Kenya", code: "+254", iso: "KE", flag: "🇰🇪" },
  { country: "Nijerya", code: "+234", iso: "NG", flag: "🇳🇬" },
  { country: "Güney Afrika", code: "+27", iso: "ZA", flag: "🇿🇦" },
  { country: "Endonezya", code: "+62", iso: "ID", flag: "🇮🇩" },
  { country: "Malezya", code: "+60", iso: "MY", flag: "🇲🇾" },
  { country: "Singapur", code: "+65", iso: "SG", flag: "🇸🇬" },
  { country: "Tayland", code: "+66", iso: "TH", flag: "🇹🇭" },
  { country: "Vietnam", code: "+84", iso: "VN", flag: "🇻🇳" },
  { country: "Filipinler", code: "+63", iso: "PH", flag: "🇵🇭" },
  { country: "Avustralya", code: "+61", iso: "AU", flag: "🇦🇺" },
  { country: "Yeni Zelanda", code: "+64", iso: "NZ", flag: "🇳🇿" },
  { country: "Brezilya", code: "+55", iso: "BR", flag: "🇧🇷" },
  { country: "Arjantin", code: "+54", iso: "AR", flag: "🇦🇷" },
  { country: "Şili", code: "+56", iso: "CL", flag: "🇨🇱" },
  { country: "Kolombiya", code: "+57", iso: "CO", flag: "🇨🇴" },
  { country: "Peru", code: "+51", iso: "PE", flag: "🇵🇪" },
  { country: "Venezuela", code: "+58", iso: "VE", flag: "🇻🇪" },
  { country: "Uruguay", code: "+598", iso: "UY", flag: "🇺🇾" },
  { country: "Malta", code: "+356", iso: "MT", flag: "🇲🇹" },
];
