// Türkiye'deki üniversiteler + vakıf meslek yüksekokulları (YÖK kaynaklı,
// devlet + vakıf, alfabetik). Profil eğitim bölümü + kulüp başvuru formu
// "Bağlı olduğunuz Üniversite" dropdown'u için.
//
// YÖK 2024 datası — 129 devlet + 78 vakıf üniversitesi + 5 vakıf MYO.
// Devlet MYO'ları kendi üniversitelerine bağlı olduğundan standalone değil
// (örn. "Marmara Üniversitesi Sosyal Bilimler MYO"); ana üniversitesi
// seçilmelidir. hangel Üniversitesi platformun resmi üniversitesidir.

export const TURKISH_UNIVERSITIES: string[] = [
  "Abdullah Gül Üniversitesi",
  "Acıbadem Mehmet Ali Aydınlar Üniversitesi",
  "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi",
  "Adıyaman Üniversitesi",
  "Adnan Menderes Üniversitesi",
  "Afyon Kocatepe Üniversitesi",
  "Afyonkarahisar Sağlık Bilimleri Üniversitesi",
  "Ağrı İbrahim Çeçen Üniversitesi",
  "Akdeniz Üniversitesi",
  "Aksaray Üniversitesi",
  "Alanya Alaaddin Keykubat Üniversitesi",
  "Alanya Hamdullah Emin Paşa Üniversitesi",
  "Altınbaş Üniversitesi",
  "Amasya Üniversitesi",
  "Anadolu Üniversitesi",
  "Anka Teknoloji Üniversitesi",
  "Ankara Bilim Üniversitesi",
  "Ankara Hacı Bayram Veli Üniversitesi",
  "Ankara Medipol Üniversitesi",
  "Ankara Müzik ve Güzel Sanatlar Üniversitesi",
  "Ankara Sosyal Bilimler Üniversitesi",
  "Ankara Üniversitesi",
  "Ankara Yıldırım Beyazıt Üniversitesi",
  "Antalya AKEV Üniversitesi",
  "Antalya Belek Üniversitesi",
  "Antalya Bilim Üniversitesi",
  "Ardahan Üniversitesi",
  "Artvin Çoruh Üniversitesi",
  "Atatürk Üniversitesi",
  "Atılım Üniversitesi",
  "Avrasya Üniversitesi",
  "Bahçeşehir Üniversitesi",
  "Balıkesir Üniversitesi",
  "Bandırma Onyedi Eylül Üniversitesi",
  "Bartın Üniversitesi",
  "Başkent Üniversitesi",
  "Batman Üniversitesi",
  "Bayburt Üniversitesi",
  "Beykent Üniversitesi",
  "Beykoz Üniversitesi",
  "Bezmiâlem Vakıf Üniversitesi",
  "Bilecik Şeyh Edebali Üniversitesi",
  "Bilkent Üniversitesi (İhsan Doğramacı)",
  "Bingöl Üniversitesi",
  "Biruni Üniversitesi",
  "Bitlis Eren Üniversitesi",
  "Boğaziçi Üniversitesi",
  "Bolu Abant İzzet Baysal Üniversitesi",
  "Burdur Mehmet Akif Ersoy Üniversitesi",
  "Bursa Teknik Üniversitesi",
  "Bursa Uludağ Üniversitesi",
  "Çağ Üniversitesi",
  "Çanakkale Onsekiz Mart Üniversitesi",
  "Çankaya Üniversitesi",
  "Çankırı Karatekin Üniversitesi",
  "Çukurova Üniversitesi",
  "Demiroğlu Bilim Üniversitesi",
  "Dicle Üniversitesi",
  "Doğuş Üniversitesi",
  "Dokuz Eylül Üniversitesi",
  "Düzce Üniversitesi",
  "Ege Üniversitesi",
  "Erciyes Üniversitesi",
  "Erzincan Binali Yıldırım Üniversitesi",
  "Erzurum Teknik Üniversitesi",
  "Eskişehir Osmangazi Üniversitesi",
  "Eskişehir Teknik Üniversitesi",
  "Faruk Saraç Tasarım Meslek Yüksekokulu",
  "Fatih Sultan Mehmet Vakıf Üniversitesi",
  "Fenerbahçe Üniversitesi",
  "Fırat Üniversitesi",
  "Galatasaray Üniversitesi",
  "Gaziantep Üniversitesi",
  "Gaziantep İslam Bilim ve Teknoloji Üniversitesi",
  "Gazi Üniversitesi",
  "Gaziosmanpaşa Üniversitesi",
  "Gebze Teknik Üniversitesi",
  "Gedik Üniversitesi",
  "Giresun Üniversitesi",
  "Gümüşhane Üniversitesi",
  "Hacettepe Üniversitesi",
  "Hakkari Üniversitesi",
  "Haliç Üniversitesi",
  "Harran Üniversitesi",
  "Hasan Kalyoncu Üniversitesi",
  "Hatay Mustafa Kemal Üniversitesi",
  "Hitit Üniversitesi",
  "Iğdır Üniversitesi",
  "Isparta Uygulamalı Bilimler Üniversitesi",
  "İbn Haldun Üniversitesi",
  "İstanbul 29 Mayıs Üniversitesi",
  "İstanbul Arel Üniversitesi",
  "İstanbul Atlas Üniversitesi",
  "İstanbul Aydın Üniversitesi",
  "İstanbul Beykent Üniversitesi",
  "İstanbul Bilgi Üniversitesi",
  "İstanbul Esenyurt Üniversitesi",
  "İstanbul Galata Üniversitesi",
  "İstanbul Gelişim Üniversitesi",
  "İstanbul Kent Üniversitesi",
  "İstanbul Kültür Üniversitesi",
  "İstanbul Medeniyet Üniversitesi",
  "İstanbul Medipol Üniversitesi",
  "İstanbul Nişantaşı Üniversitesi",
  "İstanbul Okan Üniversitesi",
  "İstanbul Rumeli Üniversitesi",
  "İstanbul Sabahattin Zaim Üniversitesi",
  "İstanbul Sağlık ve Sosyal Bilimler Meslek Yüksekokulu",
  "İstanbul Sağlık Bilimleri Üniversitesi",
  "İstanbul Şişli Meslek Yüksekokulu",
  "İstanbul Teknik Üniversitesi",
  "İstanbul Ticaret Üniversitesi",
  "İstanbul Topkapı Üniversitesi",
  "İstanbul Üniversitesi",
  "İstanbul Üniversitesi-Cerrahpaşa",
  "İstanbul Yeni Yüzyıl Üniversitesi",
  "İstinye Üniversitesi",
  "İzmir Bakırçay Üniversitesi",
  "İzmir Demokrasi Üniversitesi",
  "İzmir Ekonomi Üniversitesi",
  "İzmir Kâtip Çelebi Üniversitesi",
  "İzmir Tınaztepe Üniversitesi",
  "İzmir Yüksek Teknoloji Enstitüsü",
  "Kadir Has Üniversitesi",
  "Kafkas Üniversitesi",
  "Kahramanmaraş İstiklal Üniversitesi",
  "Kahramanmaraş Sütçü İmam Üniversitesi",
  "Kapadokya Üniversitesi",
  "Karabük Üniversitesi",
  "Karadeniz Teknik Üniversitesi",
  "Karamanoğlu Mehmetbey Üniversitesi",
  "Kastamonu Üniversitesi",
  "Kayseri Üniversitesi",
  "Kıbrıs Sağlık ve Toplum Bilimleri Üniversitesi",
  "Kilis 7 Aralık Üniversitesi",
  "Kırıkkale Üniversitesi",
  "Kırklareli Üniversitesi",
  "Kırşehir Ahi Evran Üniversitesi",
  "Koç Üniversitesi",
  "Kocaeli Sağlık ve Teknoloji Üniversitesi",
  "Kocaeli Üniversitesi",
  "Konya Gıda ve Tarım Üniversitesi",
  "Konya Teknik Üniversitesi",
  "KTO Karatay Üniversitesi",
  "Kütahya Dumlupınar Üniversitesi",
  "Kütahya Sağlık Bilimleri Üniversitesi",
  "Lokman Hekim Üniversitesi",
  "Maltepe Üniversitesi",
  "Manisa Celal Bayar Üniversitesi",
  "Mardin Artuklu Üniversitesi",
  "Marmara Üniversitesi",
  "Marmara Sağlık Hizmetleri Meslek Yüksekokulu",
  "MEF Üniversitesi",
  "Mersin Üniversitesi",
  "Mimar Sinan Güzel Sanatlar Üniversitesi",
  "Munzur Üniversitesi",
  "Muğla Sıtkı Koçman Üniversitesi",
  "Muş Alparslan Üniversitesi",
  "Necmettin Erbakan Üniversitesi",
  "Nevşehir Hacı Bektaş Veli Üniversitesi",
  "Niğde Ömer Halisdemir Üniversitesi",
  "Nuh Naci Yazgan Üniversitesi",
  "Ondokuz Mayıs Üniversitesi",
  "Ordu Üniversitesi",
  "Orta Doğu Teknik Üniversitesi (ODTÜ)",
  "Osmaniye Korkut Ata Üniversitesi",
  "Özyeğin Üniversitesi",
  "Pamukkale Üniversitesi",
  "Piri Reis Üniversitesi",
  "Plato Meslek Yüksekokulu",
  "Recep Tayyip Erdoğan Üniversitesi",
  "Sabancı Üniversitesi",
  "Sağlık Bilimleri Üniversitesi",
  "Sakarya Üniversitesi",
  "Sakarya Uygulamalı Bilimler Üniversitesi",
  "Samsun Üniversitesi",
  "Sanko Üniversitesi",
  "Selçuk Üniversitesi",
  "Siirt Üniversitesi",
  "Sinop Üniversitesi",
  "Sivas Bilim ve Teknoloji Üniversitesi",
  "Sivas Cumhuriyet Üniversitesi",
  "Süleyman Demirel Üniversitesi",
  "Şırnak Üniversitesi",
  "Tarsus Üniversitesi",
  "Tekirdağ Namık Kemal Üniversitesi",
  "TOBB Ekonomi ve Teknoloji Üniversitesi",
  "Tokat Gaziosmanpaşa Üniversitesi",
  "Toros Üniversitesi",
  "Trabzon Üniversitesi",
  "Trakya Üniversitesi",
  "Türk-Alman Üniversitesi",
  "Türk Hava Kurumu Üniversitesi",
  "Türkiye Ulaştırma ve Lojistik Üniversitesi",
  "Uşak Üniversitesi",
  "Üsküdar Üniversitesi",
  "Van Yüzüncü Yıl Üniversitesi",
  "Yalova Üniversitesi",
  "Yaşar Üniversitesi",
  "Yeditepe Üniversitesi",
  "Yıldız Teknik Üniversitesi",
  "Yozgat Bozok Üniversitesi",
  "Zonguldak Bülent Ecevit Üniversitesi",
  // hangel Üniversitesi — platformun resmi üniversitesi; listenin en sonunda.
  "hangel Üniversitesi",
];

export const EDUCATION_LEVELS = [
  "Lise",
  "Önlisans",
  "Lisans",
  "Yüksek Lisans",
  "Doktora",
] as const;

export type EducationLevel = typeof EDUCATION_LEVELS[number];

export const EDUCATION_STATUS = [
  "Devam Ediyor",
  "Mezun",
  "Terk",
] as const;

export type EducationStatus = typeof EDUCATION_STATUS[number];

// Türkiye üniversitelerindeki yaygın FAKÜLTELER (alfabetik). Profil eğitim
// bölümünde fakülte dropdown'u için. Bulamayan "Diğer" seçer.
export const FACULTIES: string[] = [
  "Açıköğretim Fakültesi",
  "Diş Hekimliği Fakültesi",
  "Eczacılık Fakültesi",
  "Edebiyat Fakültesi",
  "Eğitim Bilimleri Fakültesi",
  "Eğitim Fakültesi",
  "Fen Fakültesi",
  "Fen-Edebiyat Fakültesi",
  "Güzel Sanatlar Fakültesi",
  "Güzel Sanatlar, Tasarım ve Mimarlık Fakültesi",
  "Havacılık ve Uzay Bilimleri Fakültesi",
  "Hemşirelik Fakültesi",
  "Hukuk Fakültesi",
  "İktisadi ve İdari Bilimler Fakültesi",
  "İktisat Fakültesi",
  "İlahiyat Fakültesi",
  "İletişim Fakültesi",
  "İnsan ve Toplum Bilimleri Fakültesi",
  "İşletme Fakültesi",
  "İslami İlimler Fakültesi",
  "Mimarlık Fakültesi",
  "Mimarlık ve Tasarım Fakültesi",
  "Mühendislik Fakültesi",
  "Mühendislik-Mimarlık Fakültesi",
  "Mühendislik ve Doğa Bilimleri Fakültesi",
  "Orman Fakültesi",
  "Sağlık Bilimleri Fakültesi",
  "Sanat ve Tasarım Fakültesi",
  "Siyasal Bilgiler Fakültesi",
  "Spor Bilimleri Fakültesi",
  "Su Ürünleri Fakültesi",
  "Teknoloji Fakültesi",
  "Tıp Fakültesi",
  "Turizm Fakültesi",
  "Uygulamalı Bilimler Fakültesi",
  "Veteriner Fakültesi",
  "Ziraat Fakültesi",
  "Diğer",
];

// Türkiye üniversitelerindeki yaygın BÖLÜMLER (alfabetik, kümülatif). Profil
// eğitim bölümünde bölüm dropdown'u için. Bulamayan "Diğer" seçer.
export const DEPARTMENTS: string[] = [
  "Acil Yardım ve Afet Yönetimi",
  "Adalet",
  "Aktüerya Bilimleri",
  "Antropoloji",
  "Arkeoloji",
  "Astronomi ve Uzay Bilimleri",
  "Bankacılık ve Finans",
  "Bankacılık ve Sigortacılık",
  "Beden Eğitimi ve Spor Öğretmenliği",
  "Beslenme ve Diyetetik",
  "Bilgi ve Belge Yönetimi",
  "Bilgisayar Mühendisliği",
  "Bilgisayar Programcılığı",
  "Bilişim Sistemleri Mühendisliği",
  "Biyoloji",
  "Biyomedikal Mühendisliği",
  "Çalışma Ekonomisi ve Endüstri İlişkileri",
  "Çevre Mühendisliği",
  "Coğrafya",
  "Dil ve Konuşma Terapisi",
  "Diş Hekimliği",
  "Ebelik",
  "Eczacılık",
  "Edebiyat",
  "Ekonometri",
  "Ekonomi",
  "Elektrik-Elektronik Mühendisliği",
  "Elektronik ve Haberleşme Mühendisliği",
  "Endüstri Mühendisliği",
  "Endüstri Ürünleri Tasarımı",
  "Enerji Sistemleri Mühendisliği",
  "Ergoterapi",
  "Fars Dili ve Edebiyatı",
  "Felsefe",
  "Fen Bilgisi Öğretmenliği",
  "Fizik",
  "Fizyoterapi ve Rehabilitasyon",
  "Gastronomi ve Mutfak Sanatları",
  "Gazetecilik",
  "Gemi İnşaatı ve Gemi Makineleri Mühendisliği",
  "Genetik ve Biyomühendislik",
  "Gıda Mühendisliği",
  "Görsel İletişim Tasarımı",
  "Grafik Tasarımı",
  "Halkla İlişkiler ve Tanıtım",
  "Harita Mühendisliği (Geomatik)",
  "Havacılık ve Uzay Mühendisliği",
  "Hemşirelik",
  "Hukuk",
  "İç Mimarlık",
  "İç Mimarlık ve Çevre Tasarımı",
  "İktisat",
  "İlahiyat",
  "İletişim Bilimleri",
  "İlköğretim Matematik Öğretmenliği",
  "İngiliz Dili ve Edebiyatı",
  "İngilizce Öğretmenliği",
  "İnşaat Mühendisliği",
  "İstatistik",
  "İşletme",
  "İşletme Mühendisliği",
  "Jeofizik Mühendisliği",
  "Jeoloji Mühendisliği",
  "Kamu Yönetimi",
  "Kimya",
  "Kimya Mühendisliği",
  "Maden Mühendisliği",
  "Makine Mühendisliği",
  "Maliye",
  "Malzeme Bilimi ve Mühendisliği",
  "Matematik",
  "Matematik Mühendisliği",
  "Mekatronik Mühendisliği",
  "Metalurji ve Malzeme Mühendisliği",
  "Mimarlık",
  "Moleküler Biyoloji ve Genetik",
  "Muhasebe ve Finans Yönetimi",
  "Müzik",
  "Mütercim ve Tercümanlık",
  "Odyoloji",
  "Okul Öncesi Öğretmenliği",
  "Orman Mühendisliği",
  "Otomotiv Mühendisliği",
  "Özel Eğitim Öğretmenliği",
  "Pazarlama",
  "Petrol ve Doğal Gaz Mühendisliği",
  "Peyzaj Mimarlığı",
  "Psikoloji",
  "Radyo, Televizyon ve Sinema",
  "Reklamcılık",
  "Rehberlik ve Psikolojik Danışmanlık",
  "Sağlık Yönetimi",
  "Sanat Tarihi",
  "Sınıf Öğretmenliği",
  "Sigortacılık ve Risk Yönetimi",
  "Sinema ve Televizyon",
  "Siyaset Bilimi ve Kamu Yönetimi",
  "Siyaset Bilimi ve Uluslararası İlişkiler",
  "Sosyal Bilgiler Öğretmenliği",
  "Sosyal Hizmet",
  "Sosyoloji",
  "Spor Yöneticiliği",
  "Su Ürünleri Mühendisliği",
  "Şehir ve Bölge Planlama",
  "Tarih",
  "Tekstil Mühendisliği",
  "Tıp",
  "Turizm İşletmeciliği",
  "Turizm ve Otel İşletmeciliği",
  "Türk Dili ve Edebiyatı",
  "Türkçe Öğretmenliği",
  "Uçak Mühendisliği",
  "Uçak ve Uzay Mühendisliği",
  "Uluslararası İlişkiler",
  "Uluslararası Ticaret ve İşletmecilik",
  "Uluslararası Ticaret ve Lojistik",
  "Veterinerlik",
  "Yapay Zeka Mühendisliği",
  "Yazılım Mühendisliği",
  "Yönetim Bilişim Sistemleri",
  "Ziraat Mühendisliği",
  "Diğer",
];
