import 'package:flutter/material.dart';

import '../constants/app_theme.dart';
import '../models/brand_model.dart';
import '../models/stk_model.dart';

List<Color> randomColors = [
  AppTheme.blue,
  AppTheme.green,
  AppTheme.yellow,
  AppTheme.red,
  AppTheme.primaryColor,
];
List<StkModel> stkModels = [
  StkModel(
    name: "Güvercin Sevenler Derneği",
    country: "Türkiye",
    city: "İstanbul",
    fieldOfBenefit: "Hayvan Hakları",
    inEarthquakeZone: false,
    specialStatus: "Sivil Toplum Kuruluşu",
    creationDate: DateTime(2005, 9, 27),
    bannerImage: "https://example.com/guvercin-banner.jpg",
    detailText: "Kuş severlerin bir araya geldiği ve güvercinlerin haklarını savunan bir dernektir.",
    link: "https://www.guvercinseverler.org/",
    type: "Dernek",
    donorCount: 15000,
    categories: [
      "Hayvan Hakları",
      "Sosyal Değişim",
    ],
  ),
  StkModel(
    name: "Bağımlılıkla Mücadele Derneği",
    country: "Türkiye",
    city: "Ankara",
    fieldOfBenefit: "Bağımlılıkla Mücadele",
    inEarthquakeZone: false,
    specialStatus: "Sivil Toplum Kuruluşu",
    creationDate: DateTime(2003, 4, 11),
    bannerImage: "https://example.com/bagimlilik-banner.jpg",
    detailText: "Bağımlılıkla mücadele ederek toplumda sağlıklı bir yaşamı teşvik eden bir dernektir.",
    link: "https://www.bagimlilikla-mucadele.org/",
    type: "Dernek",
    donorCount: 20000,
    categories: [
      "Bağımlılıkla Mücadele",
      "Sosyal Değişim",
    ],
  ),
  StkModel(
    name: "Fırsat Eşitliği Derneği",
    country: "Türkiye",
    city: "İzmir",
    fieldOfBenefit: "Eşitlik",
    inEarthquakeZone: false,
    specialStatus: "Sivil Toplum Kuruluşu",
    creationDate: DateTime(2006, 8, 5),
    bannerImage: "https://example.com/esitlik-banner.jpg",
    detailText: "Toplumda fırsat eşitliği ve adaleti destekleyerek sosyal değişim yaratmayı amaçlar.",
    link: "https://www.firsat-esitligi.org/",
    type: "Dernek",
    donorCount: 18000,
    categories: [
      "Eşitlik",
      "Sosyal Değişim",
    ],
  ),
  StkModel(
    name: "Bergamalılar Derneği",
    country: "Türkiye",
    city: "Bergama",
    fieldOfBenefit: "Kültürel Miras",
    inEarthquakeZone: true,
    specialStatus: "Sivil Toplum Kuruluşu",
    creationDate: DateTime(1998, 12, 19),
    bannerImage: "https://example.com/bergamalar-banner.jpg",
    detailText: "Bergama'nın kültürel mirasını korumayı ve tanıtmayı amaçlayan bir dernektir.",
    link: "https://www.bergamalar.org.tr/",
    type: "Özel İzinli",
    donorCount: 12000,
    categories: [
      "Kültürel Miras",
      "Sosyal Değişim",
    ],
  ),
  StkModel(
    name: "Kırsal Kalkınma Derneği",
    country: "Türkiye",
    city: "Adana",
    fieldOfBenefit: "Kırsal Kalkınma",
    inEarthquakeZone: false,
    specialStatus: "Sivil Toplum Kuruluşu",
    creationDate: DateTime(2000, 6, 8),
    bannerImage: "https://example.com/kirsal-kalkinma-banner.jpg",
    detailText: "Kırsal bölgelerde yaşayan insanların ekonomik ve sosyal kalkınmasını destekler.",
    link: "https://www.kirsal-kalkinma.org.tr/",
    type: "Vakıf",
    donorCount: 25000,
    categories: [
      "Kırsal Kalkınma",
      "Sosyal Değişim",
    ],
  ),
];
