// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      print("Web sürümüne geçiliyor...");
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1_y0i7LWYe5jWAXP2caRLyyjY05a_DBg',
    appId: '1:681395322694:web:ea61354f0d8652cfa06f47',
    messagingSenderId: '681395322694',
    projectId: 'hangel-1',
    authDomain: 'hangel-1.firebaseapp.com',
    storageBucket: 'hangel-1.appspot.com',
    measurementId: 'G-MK1E9P7YZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2QiIo1G-iinW3wkIyuyp9Rm8gIK4yFC8',
    appId: '1:681395322694:android:01a26bde4e4527b4a06f47',
    messagingSenderId: '681395322694',
    projectId: 'hangel-1',
    storageBucket: 'hangel-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRvxqC1JQsCWNvNZzuZPsfJGu07XIxRu8',
    appId: '1:681395322694:ios:5100a4f83aba6d57a06f47',
    messagingSenderId: '681395322694',
    projectId: 'hangel-1',
    storageBucket: 'hangel-1.appspot.com',
    iosClientId: '681395322694-ljene7v6nks8627psmfv4d984stnrklc.apps.googleusercontent.com',
    iosBundleId: 'com.hangel.ios.app',
  );
}
